server:
  port: 8003

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000

reactive:
  feign:
    loadbalancer:
      enabled: true
    circuit:
      breaker:
        enabled: false

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.95.41:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.95.41:8080
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.95.18:3306/oauth2?setUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 300000
      connection-test-query: SELECT 1

  redis:
    timeout: 5000
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

mybatis:
  type-aliases-package: com.somnus.microservice.provider.cpc.model.domain
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

dubbo:
  application:
    name: cpc
  registry:
    address: nacos://192.168.95.41:8848
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  scan:
    basePackages: com.somnus.microservice.provider.cpc.web.rpc

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:logback-spring.xml
#logstash:
#  kafka:
#    bootstrap-servers: 192.168.95.10:9092,192.168.95.11:9092,192.168.95.12:9092
#    topic: wt-cpc-test

elastic:
  job:
    zk:
      namespace: elasticjob
      serverLists: 192.168.95.33:2181,192.168.95.33:2182,192.168.95.33:2183
