server:
  port: 8000

spring:
  security:
    oauth2:
      resourceserver:
        jwt: #配置RSA的公钥访问地址
          jwk-set-uri: http://localhost:8002/oauth2/jwks
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.95.41:8848
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      discovery:
        locator:
          enabled: true
      default-filters:
        - StripPrefix=1
      routes:
        - id: uac
          uri: lb://uac
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"
          predicates:
            - Method=GET,POST
            - Path=/uac/**
        - id: cpc
          uri: lb://cpc
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"
          predicates:
            - Method=GET,POST
            - Path=/cpc/**
        - id: oauth2
          uri: lb://oauth2
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"
          predicates:
            - Method=GET,POST
            - Path=/oauth2/**
  redis:
    timeout: 5000
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

jwt:
  token:
    expired: 12
    refresh:
      expired: 12

